name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Escribe DESTROY para confirmar"
        required: true
        default: "DESTROY"

jobs:
  destroy:
    runs-on: ubuntu-latest
    concurrency: terraform
    defaults:
      run:
        working-directory: terraform

    # ⬇⬇⬇  AÑADE ESTO
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "0"
      TF_VAR_my_ip_cidr: ${{ secrets.MY_IP_CIDR }}
      TF_VAR_key_pair_name: ${{ secrets.KEY_PAIR_NAME }}
      TF_VAR_alarm_email: ${{ secrets.ALARM_EMAIL }}
      TF_VAR_aws_region: us-east-1
      TF_VAR_instance_type: t3.micro

      # si usas backend S3, mantén también estas (ajústalas a tu repo)
      TF_STATE_BUCKET: matiaslb14-tfstate-ue1
      TF_STATE_KEY: cloud-security/terraform.tfstate
      TF_LOCK_TABLE: matiaslb14-terraform-locks
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Verificar confirmación
        if: ${{ github.event.inputs.confirm != 'DESTROY' }}
        run: |
          echo "Debes escribir DESTROY para continuar." >&2
          exit 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Si usas backend S3 via flags, reconfigura:
      - name: Terraform Init (S3 backend)
        run: |
          terraform init -no-color -input=false -reconfigure \
            -backend-config="bucket=$TF_STATE_BUCKET" \
            -backend-config="key=$TF_STATE_KEY" \
            -backend-config="region=$AWS_REGION" \
            -backend-config="dynamodb_table=$TF_LOCK_TABLE" \
            -backend-config="encrypt=true"

      - name: terraform destroy
        run: terraform destroy -no-color -input=false -auto-approve
