name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Escribe DESTROY para confirmar la eliminación"
        required: true
        default: "DESTROY"

# Unificado con apply
concurrency:
  group: terraform
  cancel-in-progress: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Verificar confirmación
        if: ${{ github.event.inputs.confirm != 'DESTROY' }}
        run: |
          echo "Debes escribir DESTROY para continuar." >&2
          exit 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: terraform init
        env:
          TF_IN_AUTOMATION: "true"
          TF_INPUT: "0"
        run: terraform init -no-color -input=false -reconfigure

      - name: terraform destroy
        env:
          TF_IN_AUTOMATION: "true"
          TF_INPUT: "0"
        run: terraform destroy -no-color -auto-approve
