name: Terraform Pipeline

on:
  push:
    branches: [ main ]

# evita carreras: si hay un commit nuevo, cancela el run anterior
concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    timeout-minutes: 25

    # variables para Terraform y CI sin entrada interactiva
    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: 0
      TF_VAR_my_ip_cidr: ${{ secrets.MY_IP_CIDR }}          # ej: 181.226.xxx.xxx/32
      TF_VAR_key_pair_name: ${{ secrets.KEY_PAIR_NAME }}    # nombre del key pair (p.e. "mati-key")
      TF_VAR_alarm_email: ${{ secrets.ALARM_EMAIL }}        # opcional si no la usas
      TF_VAR_aws_region: us-east-1                          # opcional (tienes default en variables.tf)

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -no-color

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -out=tfplan

      - name: Terraform Apply
        run: terraform apply -no-color -input=false -auto-approve tfplan
